import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TestProvider } from "./context/TestContext";
import { Toaster } from "sonner";
import { AuthProvider } from './context/AuthContext'
import { InstrumentProvider } from "./context/InstrumentContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TestProvider>
          <Toaster
            theme='dark'
            position='top-center'
            richColors={true}
            toastOptions={{
              className: 'toast-font'
            }}
          />
          <AuthProvider>
            <InstrumentProvider>
              {children}
            </InstrumentProvider>
          </AuthProvider>
        </TestProvider>
      </body>
    </html>
  );
}
